- name: clientserver
  shortName: Run as clientserver service
  long: ""
  service:
    ports:
    - name: clientserver
      wireProtocol: tcp
      protocol: grpc
      public: true
      defaultRoutes: []
      flagName: grpc-port
      flagUsage: GRPC Port to listen on
      configName: clientserver.grpc.port
      defaultValue: 50051
      env:
      - CLIENTSERVER_GRPC_PORT
    healthCheckPorts:
    - name: healthcheck-grpc
      wireProtocol: tcp
      protocol: grpc
      public: false
      defaultRoutes: []
      flagName: healthcheck-port
      flagUsage: Port to listen on for services that support a health check
      configName: healthcheck.port
      defaultValue: 5051
      env:
      - EXPLODING_KITTENS_HEALTHCHECK_PORT
    - name: healthcheck-web
      wireProtocol: tcp
      protocol: http
      public: false
      defaultRoutes:
      - /healthz
      - /readyz
      flagName: healthcheck-web-port
      flagUsage: Port to listen on for services that support a health check
      configName: healthcheck.web.port
      defaultValue: 5052
      env:
      - EXPLODING_KITTENS_HEALTHCHECK_WEB_PORT
    defaultDatabaseName: ""
  config:
  - name: dataprovider-url
    usage: Dataprovider connection URL
    default: http://dataprovider:50055
    valueType: string
    path: clientserver.dataprovider.url
    env:
    - CLIENTSERVER_DATAPROVIDER_URL
  - name: gameengineserver-url
    usage: Game Engine Server connection URL
    default: http://gameengineserver:50054
    valueType: string
    path: clientserver.gameengineserver.url
    env:
    - CLIENTSERVER_GAMEENGINESERVER_URL
  - name: grpc-port
    usage: GRPC Port to listen on
    default: 50051
    valueType: int64
    path: clientserver.grpc.port
    env:
    - CLIENTSERVER_GRPC_PORT
  - name: id
    usage: Unique identifier for this services
    default: ""
    valueType: string
    path: clientserver.id
    env:
    - CLIENTSERVER_ID
  - name: nats-consumer-replicas
    usage: Number of times to replicate consumers
    default: 1
    valueType: int64
    path: clientserver.nats.consumer.replicas
    env:
    - CLIENTSERVER_NATS_CONSUMER_REPLICAS
  - name: nats-consumer-storage
    usage: Storage type to use for consumers
    default: memory
    valueType: string
    path: clientserver.nats.consumer.storage
    env:
    - CLIENTSERVER_NATS_CONSUMER_STORAGE
  - name: nats-stream-replicas
    usage: Number of times to replicate steams
    default: 1
    valueType: int64
    path: clientserver.nats.stream.replicas
    env:
    - CLIENTSERVER_NATS_STREAM_REPLICAS
  - name: nats-stream-storage
    usage: Storage type to use for streams
    default: memory
    valueType: string
    path: clientserver.nats.stream.storage
    env:
    - CLIENTSERVER_NATS_STREAM_STORAGE
  - name: nats-url
    usage: Comma separated list of NATS endpoints
    default: nats:4222
    valueType: string
    path: clientserver.nats.url
    env:
    - CLIENTSERVER_NATS_URL
  - name: token-signing-key
    usage: Signing key used for service to service tokens
    default: ""
    valueType: string
    path: clientserver.secrets.token_signing_key
    env:
    - CLIENTSERVER_SECRETS_TOKEN_SIGNING_KEY
  - name: userserver-url
    usage: Userserver connection URL
    default: http://userserver:50052
    valueType: string
    path: clientserver.userserver.url
    env:
    - CLIENTSERVER_USERSERVER_URL
  - name: healthcheck-host
    usage: Host to listen on for services that support a health check
    default: localhost
    valueType: string
    path: healthcheck.host
    env:
    - EXPLODING_KITTENS_HEALTHCHECK_HOST
  - name: healthcheck-port
    usage: Port to listen on for services that support a health check
    default: 5051
    valueType: int
    path: healthcheck.port
    env:
    - EXPLODING_KITTENS_HEALTHCHECK_PORT
  - name: healthcheck-web-port
    usage: Port to listen on for services that support a health check
    default: 5052
    valueType: int
    path: healthcheck.web.port
    env:
    - EXPLODING_KITTENS_HEALTHCHECK_WEB_PORT
  - name: jaeger-url
    usage: URL to send Jaeger data to
    default: ""
    valueType: string
    path: jaeger.url
    env:
    - EXPLODING_KITTENS_JAEGER_URL
  - name: log-level
    usage: log level to use
    default: info
    valueType: string
    path: log.level
    env:
    - LOG_LEVEL
  - name: otel-url
    usage: URL to send OpenTelemetry data to
    default: localhost:30080
    valueType: string
    path: otel.url
    env:
    - EXPLODING_KITTENS_OTEL_URL
  - name: service
    usage: which service to run
    default: ""
    valueType: string
    path: service
    env:
    - EXPLODING_KITTENS_SERVICE
