services:
  userserver:
    image: pocker:latest
    container_name: ${COMPOSE_PROJECT_NAME:-test}_userserver
    hostname: userserver
    environment:
      "USERSERVER_ID": "00000000-0000-0000-0000-000000000001"
      "USERSERVER_SECRETS_TOKEN_SIGNING_KEY": "secr3t_p0ck3r"
    ports:
      - 8020:8020 # GRPC port
    networks:
      fs_test_net:
        ipv4_address: "172.16.244.16"
    healthcheck:
      test: [ "CMD-SHELL", "/app check http localhost:5052/healthz" ]
      start_period: 90s
      interval: 5s
      timeout: 4s
      retries: 30

networks:
  fs_test_net:
    name: fs_test_net
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: "172.16.244.0/23"