services:
  phase_one_leader:
    image: ${ALPINE_CONTAINER_IMAGE}
    container_name: ${COMPOSE_PROJECT_NAME:-test}_phase_one_leader
    entrypoint: echo "Phase One Leader Launch" && exit 0
    networks:
      fs_test_net:
        ipv4_address: "172.16.244.7"
    depends_on:
      kittens_database:
        condition: service_healthy
      kittens_nats:
        condition: service_healthy

  kittens_nats:
    hostname: nats
    image: ${NATS_CONTAINER_IMAGE}
    container_name: ${COMPOSE_PROJECT_NAME:-test}_nats
    entrypoint: "nats-server --jetstream --name nats --http_port 8222"
    ports:
      - "4223:4222"
      - "8223:8222"
    networks:
      fs_test_net:
        ipv4_address: "172.16.244.41"
    healthcheck:
      test: >-
        wget
        --no-verbose
        --tries=1
        --spider
        http://localhost:8222/healthz
        ||
        exit 1
      start_period: 90s
      interval: 5s
      timeout: 4s
      retries: 30

  kittens_database:
    image: ${POSTGRES_CONTAINER_IMAGE}
    container_name: ${COMPOSE_PROJECT_NAME:-test}_database
    hostname: kittens_database
    environment:
      "POSTGRES_DB": "postgres"
      "POSTGRES_USER": "root_admin"
      "POSTGRES_PASSWORD": "admin@123"
      "POSTGRES_MULTIPLE_DATABASES": "userserver:userserver;dataprovider:dataprovider;"
    ports:
      - "5432:5432"
    networks:
      fs_test_net:
        ipv4_address: "172.16.244.31"
    volumes:
      - ./db/create_databases.sh:/docker-entrypoint-initdb.d/create_databases.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      start_period: 90s
      interval: 5s
      timeout: 4s
      retries: 30   

  dataprovider:
    image: kittens:latest
    container_name: ${COMPOSE_PROJECT_NAME:-test}_dataprovider
    hostname: dataprovider
    environment:
      "EXPLODING_KITTENS_SERVICE": "dataprovider"
      "DATAPROVIDER_ID": "00000000-0000-0000-0000-000000000005"
      "DATAPROVIDER_SECRETS_TOKEN_SIGNING_KEY": "secr3t_p0ck3r"
      "DATAPROVIDER_DB_URL": "postgres://root_admin:admin@123@kittens_database:5432/dataprovider?sslmode=disable"
      "DATAPROVIDER_GRPC_PORT": 50055
    ports:
      - 50055:50055 # GRPC port
    networks:
      fs_test_net:
        ipv4_address: "172.16.244.42"
    healthcheck:
      test: [ "CMD-SHELL", "/app check http localhost:5052/healthz" ]
      start_period: 90s
      interval: 5s
      timeout: 4s
      retries: 30
    depends_on:
      phase_one_leader:
        condition: service_completed_successfully 

  clientserver:
    image: kittens:latest
    container_name: ${COMPOSE_PROJECT_NAME:-test}_clientserver
    hostname: clientserver
    environment:
      "EXPLODING_KITTENS_SERVICE": "clientserver"
      "CLIENTSERVER_ID": "00000000-0000-0000-0000-000000000001"
      "CLIENTSERVER_SECRETS_TOKEN_SIGNING_KEY": "secr3t_p0ck3r"
      "CLIENTSERVER_GRPC_PORT": 50051
      "CLIENTSERVER_NATS_URL": "nats:4222"
    ports:
      - 50051:50051 # GRPC port
    networks:
      fs_test_net:
        ipv4_address: "172.16.244.10"
    healthcheck:
      test: [ "CMD-SHELL", "/app check http localhost:5052/healthz" ]
      start_period: 90s
      interval: 5s
      timeout: 4s
      retries: 30
    depends_on:
      phase_one_leader:
        condition: service_completed_successfully 

  userserver:
    image: kittens:latest
    container_name: ${COMPOSE_PROJECT_NAME:-test}_userserver
    hostname: userserver
    environment:
      "EXPLODING_KITTENS_SERVICE": "userserver"
      "USERSERVER_ID": "00000000-0000-0000-0000-000000000002"
      "USERSERVER_SECRETS_TOKEN_SIGNING_KEY": "secr3t_p0ck3r"
      "USERSERVER_DB_URL": "postgres://root_admin:admin@123@kittens_database:5432/userserver?sslmode=disable"
      "USERSERVER_GRPC_PORT": 50052
    ports:
      - 50052:50052 # GRPC port
    networks:
      fs_test_net:
        ipv4_address: "172.16.244.16"
    healthcheck:
      test: [ "CMD-SHELL", "/app check http localhost:5052/healthz" ]
      start_period: 90s
      interval: 5s
      timeout: 4s
      retries: 30
    depends_on:
      phase_one_leader:
        condition: service_completed_successfully

  lobbyserver:
    image: kittens:latest
    container_name: ${COMPOSE_PROJECT_NAME:-test}_lobbyserver
    hostname: lobbyserver
    environment:
      "EXPLODING_KITTENS_SERVICE": "lobbyserver"
      "LOBBYSERVER_ID": "00000000-0000-0000-0000-000000000003"
      "LOBBYSERVER_SECRETS_TOKEN_SIGNING_KEY": "secr3t_p0ck3r"
      "LOBBYSERVER_GRPC_PORT": 50053
      "LOBBYSERVER_NATS_URL": "nats:4222"
    ports:
      - 50053:50053 # GRPC port
    networks:
      fs_test_net:
        ipv4_address: "172.16.244.32"
    healthcheck:
      test: [ "CMD-SHELL", "/app check http localhost:5052/healthz" ]
      start_period: 90s
      interval: 5s
      timeout: 4s
      retries: 30
    depends_on:
      phase_one_leader:
        condition: service_completed_successfully  

  gameengineserver:
    image: kittens:latest
    container_name: ${COMPOSE_PROJECT_NAME:-test}_gameengineserver
    hostname: gameengineserver
    environment:
      "EXPLODING_KITTENS_SERVICE": "gameengineserver"
      "GAMEENGINESERVER_ID": "00000000-0000-0000-0000-000000000004"
      "GAMEENGINESERVER_SECRETS_TOKEN_SIGNING_KEY": "secr3t_p0ck3r"
      "GAMEENGINESERVER_DB_URL": "postgres://root_admin:admin@123@kittens_database:5432/gameengineserver?sslmode=disable"
      "GAMEENGINESERVER_GRPC_PORT": 50054
      "GAMEENGINESERVER_NATS_URL": "nats:4222"
    ports:
      - 50054:50054 # GRPC port
    networks:
      fs_test_net:
        ipv4_address: "172.16.244.25"
    healthcheck:
      test: [ "CMD-SHELL", "/app check http localhost:5052/healthz" ]
      start_period: 90s
      interval: 5s
      timeout: 4s
      retries: 30
    depends_on:
      phase_one_leader:
        condition: service_completed_successfully 

networks:
  fs_test_net:
    name: fs_test_net
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: "172.16.244.0/23"