// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: gameengineserver.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CardIds       []string               `protobuf:"bytes,3,rep,name=card_ids,json=cardIds,proto3" json:"card_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayCardsRequest) Reset() {
	*x = PlayCardsRequest{}
	mi := &file_gameengineserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayCardsRequest) ProtoMessage() {}

func (x *PlayCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gameengineserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayCardsRequest.ProtoReflect.Descriptor instead.
func (*PlayCardsRequest) Descriptor() ([]byte, []int) {
	return file_gameengineserver_proto_rawDescGZIP(), []int{0}
}

func (x *PlayCardsRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PlayCardsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlayCardsRequest) GetCardIds() []string {
	if x != nil {
		return x.CardIds
	}
	return nil
}

type DefuseExplodingKittenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CardId        *string                `protobuf:"bytes,3,opt,name=card_id,json=cardId,proto3,oneof" json:"card_id,omitempty"` // ID of the defuse card
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefuseExplodingKittenRequest) Reset() {
	*x = DefuseExplodingKittenRequest{}
	mi := &file_gameengineserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefuseExplodingKittenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefuseExplodingKittenRequest) ProtoMessage() {}

func (x *DefuseExplodingKittenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gameengineserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefuseExplodingKittenRequest.ProtoReflect.Descriptor instead.
func (*DefuseExplodingKittenRequest) Descriptor() ([]byte, []int) {
	return file_gameengineserver_proto_rawDescGZIP(), []int{1}
}

func (x *DefuseExplodingKittenRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *DefuseExplodingKittenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DefuseExplodingKittenRequest) GetCardId() string {
	if x != nil && x.CardId != nil {
		return *x.CardId
	}
	return ""
}

var File_gameengineserver_proto protoreflect.FileDescriptor

const file_gameengineserver_proto_rawDesc = "" +
	"\n" +
	"\x16gameengineserver.proto\x12,com.sweetloveinyourheart.kittens.gameengines\x1a\x1bgoogle/protobuf/empty.proto\"_\n" +
	"\x10PlayCardsRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bcard_ids\x18\x03 \x03(\tR\acardIds\"z\n" +
	"\x1cDefuseExplodingKittenRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1c\n" +
	"\acard_id\x18\x03 \x01(\tH\x00R\x06cardId\x88\x01\x01B\n" +
	"\n" +
	"\b_card_id2\xf4\x01\n" +
	"\x10GameEngineServer\x12c\n" +
	"\tPlayCards\x12>.com.sweetloveinyourheart.kittens.gameengines.PlayCardsRequest\x1a\x16.google.protobuf.Empty\x12{\n" +
	"\x15DefuseExplodingKitten\x12J.com.sweetloveinyourheart.kittens.gameengines.DefuseExplodingKittenRequest\x1a\x16.google.protobuf.EmptyBWZUgithub.com/sweetloveinyourheart/exploding-kittens/proto/code/gameengineserver/go;grpcb\x06proto3"

var (
	file_gameengineserver_proto_rawDescOnce sync.Once
	file_gameengineserver_proto_rawDescData []byte
)

func file_gameengineserver_proto_rawDescGZIP() []byte {
	file_gameengineserver_proto_rawDescOnce.Do(func() {
		file_gameengineserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gameengineserver_proto_rawDesc), len(file_gameengineserver_proto_rawDesc)))
	})
	return file_gameengineserver_proto_rawDescData
}

var file_gameengineserver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gameengineserver_proto_goTypes = []any{
	(*PlayCardsRequest)(nil),             // 0: com.sweetloveinyourheart.kittens.gameengines.PlayCardsRequest
	(*DefuseExplodingKittenRequest)(nil), // 1: com.sweetloveinyourheart.kittens.gameengines.DefuseExplodingKittenRequest
	(*emptypb.Empty)(nil),                // 2: google.protobuf.Empty
}
var file_gameengineserver_proto_depIdxs = []int32{
	0, // 0: com.sweetloveinyourheart.kittens.gameengines.GameEngineServer.PlayCards:input_type -> com.sweetloveinyourheart.kittens.gameengines.PlayCardsRequest
	1, // 1: com.sweetloveinyourheart.kittens.gameengines.GameEngineServer.DefuseExplodingKitten:input_type -> com.sweetloveinyourheart.kittens.gameengines.DefuseExplodingKittenRequest
	2, // 2: com.sweetloveinyourheart.kittens.gameengines.GameEngineServer.PlayCards:output_type -> google.protobuf.Empty
	2, // 3: com.sweetloveinyourheart.kittens.gameengines.GameEngineServer.DefuseExplodingKitten:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gameengineserver_proto_init() }
func file_gameengineserver_proto_init() {
	if File_gameengineserver_proto != nil {
		return
	}
	file_gameengineserver_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gameengineserver_proto_rawDesc), len(file_gameengineserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gameengineserver_proto_goTypes,
		DependencyIndexes: file_gameengineserver_proto_depIdxs,
		MessageInfos:      file_gameengineserver_proto_msgTypes,
	}.Build()
	File_gameengineserver_proto = out.File
	file_gameengineserver_proto_goTypes = nil
	file_gameengineserver_proto_depIdxs = nil
}
