// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: lobbyserver.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LobbyServer_GetLobbyData_FullMethodName = "/com.sweetloveinyourheart.kittens.lobbies.LobbyServer/GetLobbyData"
)

// LobbyServerClient is the client API for LobbyServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LobbyServerClient interface {
	// Get lobby data
	GetLobbyData(ctx context.Context, in *GetLobbyDataRequest, opts ...grpc.CallOption) (*GetLobbyDataResponse, error)
}

type lobbyServerClient struct {
	cc grpc.ClientConnInterface
}

func NewLobbyServerClient(cc grpc.ClientConnInterface) LobbyServerClient {
	return &lobbyServerClient{cc}
}

func (c *lobbyServerClient) GetLobbyData(ctx context.Context, in *GetLobbyDataRequest, opts ...grpc.CallOption) (*GetLobbyDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLobbyDataResponse)
	err := c.cc.Invoke(ctx, LobbyServer_GetLobbyData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LobbyServerServer is the server API for LobbyServer service.
// All implementations should embed UnimplementedLobbyServerServer
// for forward compatibility.
type LobbyServerServer interface {
	// Get lobby data
	GetLobbyData(context.Context, *GetLobbyDataRequest) (*GetLobbyDataResponse, error)
}

// UnimplementedLobbyServerServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLobbyServerServer struct{}

func (UnimplementedLobbyServerServer) GetLobbyData(context.Context, *GetLobbyDataRequest) (*GetLobbyDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLobbyData not implemented")
}
func (UnimplementedLobbyServerServer) testEmbeddedByValue() {}

// UnsafeLobbyServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LobbyServerServer will
// result in compilation errors.
type UnsafeLobbyServerServer interface {
	mustEmbedUnimplementedLobbyServerServer()
}

func RegisterLobbyServerServer(s grpc.ServiceRegistrar, srv LobbyServerServer) {
	// If the following call pancis, it indicates UnimplementedLobbyServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LobbyServer_ServiceDesc, srv)
}

func _LobbyServer_GetLobbyData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLobbyDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LobbyServerServer).GetLobbyData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LobbyServer_GetLobbyData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LobbyServerServer).GetLobbyData(ctx, req.(*GetLobbyDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LobbyServer_ServiceDesc is the grpc.ServiceDesc for LobbyServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LobbyServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.sweetloveinyourheart.kittens.lobbies.LobbyServer",
	HandlerType: (*LobbyServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLobbyData",
			Handler:    _LobbyServer_GetLobbyData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lobbyserver.proto",
}
