// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: gameserver.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameServer_PlayCards_FullMethodName             = "/com.sweetloveinyourheart.kittens.games.GameServer/PlayCards"
	GameServer_DefuseExplodingKitten_FullMethodName = "/com.sweetloveinyourheart.kittens.games.GameServer/DefuseExplodingKitten"
)

// GameServerClient is the client API for GameServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServerClient interface {
	PlayCards(ctx context.Context, in *PlayCardsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DefuseExplodingKitten(ctx context.Context, in *DefuseExplodingKittenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type gameServerClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServerClient(cc grpc.ClientConnInterface) GameServerClient {
	return &gameServerClient{cc}
}

func (c *gameServerClient) PlayCards(ctx context.Context, in *PlayCardsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GameServer_PlayCards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServerClient) DefuseExplodingKitten(ctx context.Context, in *DefuseExplodingKittenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GameServer_DefuseExplodingKitten_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServerServer is the server API for GameServer service.
// All implementations should embed UnimplementedGameServerServer
// for forward compatibility.
type GameServerServer interface {
	PlayCards(context.Context, *PlayCardsRequest) (*emptypb.Empty, error)
	DefuseExplodingKitten(context.Context, *DefuseExplodingKittenRequest) (*emptypb.Empty, error)
}

// UnimplementedGameServerServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameServerServer struct{}

func (UnimplementedGameServerServer) PlayCards(context.Context, *PlayCardsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayCards not implemented")
}
func (UnimplementedGameServerServer) DefuseExplodingKitten(context.Context, *DefuseExplodingKittenRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DefuseExplodingKitten not implemented")
}
func (UnimplementedGameServerServer) testEmbeddedByValue() {}

// UnsafeGameServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServerServer will
// result in compilation errors.
type UnsafeGameServerServer interface {
	mustEmbedUnimplementedGameServerServer()
}

func RegisterGameServerServer(s grpc.ServiceRegistrar, srv GameServerServer) {
	// If the following call pancis, it indicates UnimplementedGameServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameServer_ServiceDesc, srv)
}

func _GameServer_PlayCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayCardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServerServer).PlayCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameServer_PlayCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServerServer).PlayCards(ctx, req.(*PlayCardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameServer_DefuseExplodingKitten_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefuseExplodingKittenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServerServer).DefuseExplodingKitten(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameServer_DefuseExplodingKitten_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServerServer).DefuseExplodingKitten(ctx, req.(*DefuseExplodingKittenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameServer_ServiceDesc is the grpc.ServiceDesc for GameServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.sweetloveinyourheart.kittens.games.GameServer",
	HandlerType: (*GameServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlayCards",
			Handler:    _GameServer_PlayCards_Handler,
		},
		{
			MethodName: "DefuseExplodingKitten",
			Handler:    _GameServer_DefuseExplodingKitten_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gameserver.proto",
}
