// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: userserver.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest_AuthProvider int32

const (
	CreateUserRequest_GUEST  CreateUserRequest_AuthProvider = 0 // Guest user
	CreateUserRequest_GOOGLE CreateUserRequest_AuthProvider = 1 // Google SSO user
)

// Enum value maps for CreateUserRequest_AuthProvider.
var (
	CreateUserRequest_AuthProvider_name = map[int32]string{
		0: "GUEST",
		1: "GOOGLE",
	}
	CreateUserRequest_AuthProvider_value = map[string]int32{
		"GUEST":  0,
		"GOOGLE": 1,
	}
)

func (x CreateUserRequest_AuthProvider) Enum() *CreateUserRequest_AuthProvider {
	p := new(CreateUserRequest_AuthProvider)
	*p = x
	return p
}

func (x CreateUserRequest_AuthProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateUserRequest_AuthProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_userserver_proto_enumTypes[0].Descriptor()
}

func (CreateUserRequest_AuthProvider) Type() protoreflect.EnumType {
	return &file_userserver_proto_enumTypes[0]
}

func (x CreateUserRequest_AuthProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateUserRequest_AuthProvider.Descriptor instead.
func (CreateUserRequest_AuthProvider) EnumDescriptor() ([]byte, []int) {
	return file_userserver_proto_rawDescGZIP(), []int{3, 0}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix time for CreatedAt
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Unix time for UpdatedAt
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_userserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_userserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_userserver_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *User) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *User) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *User) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_userserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_userserver_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_userserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_userserver_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Username      string                         `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FullName      string                         `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	AuthProvider  CreateUserRequest_AuthProvider `protobuf:"varint,3,opt,name=auth_provider,json=authProvider,proto3,enum=com.sweetloveinyourheart.kittens.users.CreateUserRequest_AuthProvider" json:"auth_provider,omitempty"`
	Meta          *string                        `protobuf:"bytes,4,opt,name=meta,proto3,oneof" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_userserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_userserver_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateUserRequest) GetAuthProvider() CreateUserRequest_AuthProvider {
	if x != nil {
		return x.AuthProvider
	}
	return CreateUserRequest_GUEST
}

func (x *CreateUserRequest) GetMeta() string {
	if x != nil && x.Meta != nil {
		return *x.Meta
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_userserver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userserver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_userserver_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type SignInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInRequest) Reset() {
	*x = SignInRequest{}
	mi := &file_userserver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInRequest) ProtoMessage() {}

func (x *SignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userserver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInRequest.ProtoReflect.Descriptor instead.
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return file_userserver_proto_rawDescGZIP(), []int{5}
}

func (x *SignInRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SignInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`   // The user basic info
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // The session token for this user.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInResponse) Reset() {
	*x = SignInResponse{}
	mi := &file_userserver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInResponse) ProtoMessage() {}

func (x *SignInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userserver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInResponse.ProtoReflect.Descriptor instead.
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return file_userserver_proto_rawDescGZIP(), []int{6}
}

func (x *SignInResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *SignInResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_userserver_proto protoreflect.FileDescriptor

const file_userserver_proto_rawDesc = "" +
	"\n" +
	"\x10userserver.proto\x12&com.sweetloveinyourheart.kittens.users\"\xae\x01\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"S\n" +
	"\x0fGetUserResponse\x12@\n" +
	"\x04user\x18\x01 \x01(\v2,.com.sweetloveinyourheart.kittens.users.UserR\x04user\"\x82\x02\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12k\n" +
	"\rauth_provider\x18\x03 \x01(\x0e2F.com.sweetloveinyourheart.kittens.users.CreateUserRequest.AuthProviderR\fauthProvider\x12\x17\n" +
	"\x04meta\x18\x04 \x01(\tH\x00R\x04meta\x88\x01\x01\"%\n" +
	"\fAuthProvider\x12\t\n" +
	"\x05GUEST\x10\x00\x12\n" +
	"\n" +
	"\x06GOOGLE\x10\x01B\a\n" +
	"\x05_meta\"V\n" +
	"\x12CreateUserResponse\x12@\n" +
	"\x04user\x18\x01 \x01(\v2,.com.sweetloveinyourheart.kittens.users.UserR\x04user\"(\n" +
	"\rSignInRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"h\n" +
	"\x0eSignInResponse\x12@\n" +
	"\x04user\x18\x01 \x01(\v2,.com.sweetloveinyourheart.kittens.users.UserR\x04user\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token2\x8a\x03\n" +
	"\n" +
	"UserServer\x12z\n" +
	"\aGetUser\x126.com.sweetloveinyourheart.kittens.users.GetUserRequest\x1a7.com.sweetloveinyourheart.kittens.users.GetUserResponse\x12\x86\x01\n" +
	"\rCreateNewUser\x129.com.sweetloveinyourheart.kittens.users.CreateUserRequest\x1a:.com.sweetloveinyourheart.kittens.users.CreateUserResponse\x12w\n" +
	"\x06SignIn\x125.com.sweetloveinyourheart.kittens.users.SignInRequest\x1a6.com.sweetloveinyourheart.kittens.users.SignInResponseBQZOgithub.com/sweetloveinyourheart/exploding-kittens/proto/code/userserver/go;grpcb\x06proto3"

var (
	file_userserver_proto_rawDescOnce sync.Once
	file_userserver_proto_rawDescData []byte
)

func file_userserver_proto_rawDescGZIP() []byte {
	file_userserver_proto_rawDescOnce.Do(func() {
		file_userserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userserver_proto_rawDesc), len(file_userserver_proto_rawDesc)))
	})
	return file_userserver_proto_rawDescData
}

var file_userserver_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_userserver_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_userserver_proto_goTypes = []any{
	(CreateUserRequest_AuthProvider)(0), // 0: com.sweetloveinyourheart.kittens.users.CreateUserRequest.AuthProvider
	(*User)(nil),                        // 1: com.sweetloveinyourheart.kittens.users.User
	(*GetUserRequest)(nil),              // 2: com.sweetloveinyourheart.kittens.users.GetUserRequest
	(*GetUserResponse)(nil),             // 3: com.sweetloveinyourheart.kittens.users.GetUserResponse
	(*CreateUserRequest)(nil),           // 4: com.sweetloveinyourheart.kittens.users.CreateUserRequest
	(*CreateUserResponse)(nil),          // 5: com.sweetloveinyourheart.kittens.users.CreateUserResponse
	(*SignInRequest)(nil),               // 6: com.sweetloveinyourheart.kittens.users.SignInRequest
	(*SignInResponse)(nil),              // 7: com.sweetloveinyourheart.kittens.users.SignInResponse
}
var file_userserver_proto_depIdxs = []int32{
	1, // 0: com.sweetloveinyourheart.kittens.users.GetUserResponse.user:type_name -> com.sweetloveinyourheart.kittens.users.User
	0, // 1: com.sweetloveinyourheart.kittens.users.CreateUserRequest.auth_provider:type_name -> com.sweetloveinyourheart.kittens.users.CreateUserRequest.AuthProvider
	1, // 2: com.sweetloveinyourheart.kittens.users.CreateUserResponse.user:type_name -> com.sweetloveinyourheart.kittens.users.User
	1, // 3: com.sweetloveinyourheart.kittens.users.SignInResponse.user:type_name -> com.sweetloveinyourheart.kittens.users.User
	2, // 4: com.sweetloveinyourheart.kittens.users.UserServer.GetUser:input_type -> com.sweetloveinyourheart.kittens.users.GetUserRequest
	4, // 5: com.sweetloveinyourheart.kittens.users.UserServer.CreateNewUser:input_type -> com.sweetloveinyourheart.kittens.users.CreateUserRequest
	6, // 6: com.sweetloveinyourheart.kittens.users.UserServer.SignIn:input_type -> com.sweetloveinyourheart.kittens.users.SignInRequest
	3, // 7: com.sweetloveinyourheart.kittens.users.UserServer.GetUser:output_type -> com.sweetloveinyourheart.kittens.users.GetUserResponse
	5, // 8: com.sweetloveinyourheart.kittens.users.UserServer.CreateNewUser:output_type -> com.sweetloveinyourheart.kittens.users.CreateUserResponse
	7, // 9: com.sweetloveinyourheart.kittens.users.UserServer.SignIn:output_type -> com.sweetloveinyourheart.kittens.users.SignInResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_userserver_proto_init() }
func file_userserver_proto_init() {
	if File_userserver_proto != nil {
		return
	}
	file_userserver_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userserver_proto_rawDesc), len(file_userserver_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userserver_proto_goTypes,
		DependencyIndexes: file_userserver_proto_depIdxs,
		EnumInfos:         file_userserver_proto_enumTypes,
		MessageInfos:      file_userserver_proto_msgTypes,
	}.Build()
	File_userserver_proto = out.File
	file_userserver_proto_goTypes = nil
	file_userserver_proto_depIdxs = nil
}
